import type { RouteDefinition } from "./APIModels";

export const apiRoutes: RouteDefinition[] = [
  { method: "GET", path: "/v1/health", summary: "Service health", tags: ["Health"], auth: "public", handlerName: "health" },
  { method: "GET", path: "/v1/capabilities", summary: "Enabled capabilities", tags: ["Health"], auth: "public", handlerName: "capabilities" },
  { method: "GET", path: "/v1/me", summary: "Current user", tags: ["User Profile"], auth: "user", handlerName: "me" },
  { method: "PATCH", path: "/v1/me/profile", summary: "Update profile", tags: ["User Profile"], auth: "user", handlerName: "updateProfile" },
  { method: "DELETE", path: "/v1/me", summary: "Delete user", tags: ["Authentication"], auth: "user", handlerName: "deleteMe" },
  { method: "GET", path: "/v1/accessibility/profiles", summary: "List accessibility profiles", tags: ["Accessibility"], auth: "public", handlerName: "accessibilityProfiles" },
  { method: "GET", path: "/v1/preferences", summary: "Get preferences", tags: ["Preferences"], auth: "user", handlerName: "preferences" },
  { method: "PATCH", path: "/v1/preferences", summary: "Update preferences", tags: ["Preferences"], auth: "user", handlerName: "updatePreferences" },
  { method: "POST", path: "/v1/page-sessions", summary: "Create page session", tags: ["Website Processing"], auth: "user", handlerName: "createPageSession" },
  { method: "GET", path: "/v1/page-sessions", summary: "List page sessions", tags: ["Website Processing"], auth: "user", handlerName: "listPageSessions" },
  { method: "GET", path: "/v1/page-sessions/{session_id}", summary: "Get page session", tags: ["Website Processing"], auth: "user", handlerName: "getPageSession" },
  { method: "GET", path: "/v1/page-sessions/{session_id}/accessible-page", summary: "Accessible page model", tags: ["Accessibility"], auth: "user", handlerName: "accessiblePage" },
  { method: "GET", path: "/v1/page-sessions/{session_id}/events", summary: "Session events", tags: ["Website Processing"], auth: "user", handlerName: "sessionEvents" },
  { method: "DELETE", path: "/v1/page-sessions/{session_id}", summary: "Delete page session", tags: ["History"], auth: "user", handlerName: "deletePageSession" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/ai/summarize", summary: "AI summarize", tags: ["AI"], auth: "user", handlerName: "aiSummarize" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/ai/simplify", summary: "AI simplify", tags: ["AI"], auth: "user", handlerName: "aiSimplify" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/ai/chat", summary: "AI chat", tags: ["AI"], auth: "user", handlerName: "aiChat" },
  { method: "GET", path: "/v1/ai/history", summary: "AI history", tags: ["History"], auth: "user", handlerName: "aiHistory" },
  { method: "DELETE", path: "/v1/ai/history/{message_id}", summary: "Delete AI history", tags: ["History"], auth: "user", handlerName: "deleteAiHistory" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/translate", summary: "Translate", tags: ["AI"], auth: "user", handlerName: "translate" },
  { method: "GET", path: "/v1/voice/preferences", summary: "Voice preferences", tags: ["Voice"], auth: "user", handlerName: "voicePreferences" },
  { method: "PATCH", path: "/v1/voice/preferences", summary: "Update voice preferences", tags: ["Voice"], auth: "user", handlerName: "updateVoicePreferences" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/voice/tts", summary: "Text to speech", tags: ["Voice"], auth: "user", handlerName: "tts" },
  { method: "POST", path: "/v1/voice/stt", summary: "Speech to text", tags: ["Voice"], auth: "user", handlerName: "stt" },
  { method: "POST", path: "/v1/page-sessions/{session_id}/voice/command", summary: "Voice command", tags: ["Voice"], auth: "user", handlerName: "voiceCommand" },
  { method: "POST", path: "/v1/bookmarks", summary: "Create bookmark", tags: ["Bookmarks"], auth: "user", handlerName: "createBookmark" },
  { method: "GET", path: "/v1/bookmarks", summary: "List bookmarks", tags: ["Bookmarks"], auth: "user", handlerName: "bookmarks" },
  { method: "DELETE", path: "/v1/bookmarks/{bookmark_id}", summary: "Delete bookmark", tags: ["Bookmarks"], auth: "user", handlerName: "deleteBookmark" },
  { method: "POST", path: "/v1/notes", summary: "Create note", tags: ["Notes"], auth: "user", handlerName: "createNote" },
  { method: "GET", path: "/v1/notes", summary: "List notes", tags: ["Notes"], auth: "user", handlerName: "notes" },
  { method: "PATCH", path: "/v1/notes/{note_id}", summary: "Update note", tags: ["Notes"], auth: "user", handlerName: "updateNote" },
  { method: "DELETE", path: "/v1/notes/{note_id}", summary: "Delete note", tags: ["Notes"], auth: "user", handlerName: "deleteNote" },
  { method: "POST", path: "/v1/documents", summary: "Upload document", tags: ["Upload"], auth: "user", handlerName: "uploadDocument" },
  { method: "GET", path: "/v1/documents", summary: "List documents", tags: ["Upload"], auth: "user", handlerName: "documents" },
  { method: "GET", path: "/v1/documents/{document_id}", summary: "Get document", tags: ["Upload"], auth: "user", handlerName: "document" },
  { method: "DELETE", path: "/v1/documents/{document_id}", summary: "Delete document", tags: ["Upload"], auth: "user", handlerName: "deleteDocument" },
  { method: "POST", path: "/v1/security/analyze-url", summary: "Website scan", tags: ["Security"], auth: "user", handlerName: "securityAnalyzeUrl" },
  { method: "GET", path: "/v1/security/history", summary: "Security logs", tags: ["Security"], auth: "user", handlerName: "securityHistory" },
  { method: "GET", path: "/v1/security/history/{security_history_id}", summary: "Security report", tags: ["Security"], auth: "user", handlerName: "securityHistoryItem" },
  { method: "GET", path: "/v1/security/dashboard", summary: "Security dashboard", tags: ["Reports"], auth: "user", handlerName: "securityDashboard" },
  { method: "POST", path: "/v1/feedback", summary: "Feedback", tags: ["Feedback"], auth: "user", handlerName: "feedback" },
  { method: "POST", path: "/v1/analytics/events", summary: "Analytics event", tags: ["Analytics"], auth: "user", handlerName: "analyticsEvent" },
  { method: "GET", path: "/v1/public/usage", summary: "Public API usage", tags: ["Reports"], auth: "api_key", handlerName: "publicUsage" },
  { method: "POST", path: "/v1/public/page-sessions", summary: "Public page session", tags: ["Website Processing"], auth: "api_key", handlerName: "publicPageSession" },
  { method: "POST", path: "/v1/public/webhooks", summary: "Public webhooks", tags: ["Reports"], auth: "api_key", handlerName: "publicWebhooks" },
  // ---- ADHD Mode Routes ----
  { method: "GET", path: "/v1/adhd/health", summary: "ADHD mode health", tags: ["ADHD"], auth: "public", handlerName: "adhdHealth" },
  { method: "POST", path: "/v1/adhd/read-time", summary: "Estimate reading time", tags: ["ADHD"], auth: "public", handlerName: "adhdReadTime" },
  { method: "POST", path: "/v1/adhd/summary", summary: "TL;DR summary via LLM", tags: ["ADHD"], auth: "public", handlerName: "adhdSummary" },
  { method: "POST", path: "/v1/adhd/chunk", summary: "Chunk text into short paragraphs", tags: ["ADHD"], auth: "public", handlerName: "adhdChunk" },
  { method: "GET", path: "/v1/adhd/declutter-config", summary: "Declutter CSS selectors", tags: ["ADHD"], auth: "public", handlerName: "adhdDeclutterConfig" },
  { method: "GET", path: "/v1/adhd/palette", summary: "Muted color palette", tags: ["ADHD"], auth: "public", handlerName: "adhdPalette" },
  { method: "GET", path: "/v1/adhd/bookmarks", summary: "List ADHD bookmarks", tags: ["ADHD"], auth: "user", handlerName: "adhdListBookmarks" },
  { method: "POST", path: "/v1/adhd/bookmarks", summary: "Create ADHD bookmark", tags: ["ADHD"], auth: "user", handlerName: "adhdCreateBookmark" },
  { method: "DELETE", path: "/v1/adhd/bookmarks/{bookmark_id}", summary: "Delete ADHD bookmark", tags: ["ADHD"], auth: "user", handlerName: "adhdDeleteBookmark" },
  { method: "GET", path: "/v1/adhd/reading-progress", summary: "Get reading progress", tags: ["ADHD"], auth: "user", handlerName: "adhdGetReadingProgress" },
  { method: "POST", path: "/v1/adhd/reading-progress", summary: "Save reading progress", tags: ["ADHD"], auth: "user", handlerName: "adhdSaveReadingProgress" },
  // ---- Low Vision Mode Routes ----
  { method: "GET", path: "/v1/lowvision/health", summary: "Low vision mode health", tags: ["Low Vision"], auth: "public", handlerName: "lowvisionHealth" },
  { method: "GET", path: "/v1/lowvision/display-config", summary: "Display configuration (zoom, contrast, brightness, etc.)", tags: ["Low Vision"], auth: "public", handlerName: "lowvisionDisplayConfig" },
  { method: "POST", path: "/v1/lowvision/alt-text", summary: "Generate AI alt-text for images", tags: ["Low Vision"], auth: "public", handlerName: "lowvisionAltText" },
  { method: "GET", path: "/v1/lowvision/preferences", summary: "Get low vision user preferences", tags: ["Low Vision"], auth: "user", handlerName: "lowvisionGetPreferences" },
  { method: "POST", path: "/v1/lowvision/preferences", summary: "Update low vision user preferences", tags: ["Low Vision"], auth: "user", handlerName: "lowvisionUpdatePreferences" },
  { method: "POST", path: "/v1/lowvision/read-aloud-text", summary: "Clean page text for text-to-speech", tags: ["Low Vision"], auth: "public", handlerName: "lowvisionReadAloudText" },
  // ---- Astigmatism Mode Routes ----
  { method: "GET", path: "/v1/astigmatism/health", summary: "Astigmatism mode health", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismHealth" },
  { method: "GET", path: "/v1/astigmatism/config", summary: "Astigmatism correction values by severity", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismConfig" },
  { method: "GET", path: "/v1/astigmatism/toggle", summary: "Get Astigmatism mode toggle state", tags: ["Astigmatism"], auth: "user", handlerName: "astigmatismGetToggle" },
  { method: "POST", path: "/v1/astigmatism/toggle", summary: "Update Astigmatism mode toggle state", tags: ["Astigmatism"], auth: "user", handlerName: "astigmatismUpdateToggle" },
  { method: "POST", path: "/v1/astigmatism/transform", summary: "Fetch a URL and return Astigmatism-corrected HTML", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismTransform" },
  { method: "POST", path: "/v1/astigmatism/transform-json", summary: "Fetch a URL and return Astigmatism-corrected HTML as JSON", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismTransformJson" },
  { method: "POST", path: "/v1/astigmatism/preview", summary: "Before/after Astigmatism preview page", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismPreview" },
  { method: "POST", path: "/v1/astigmatism/preview-json", summary: "Before/after Astigmatism preview page as JSON", tags: ["Astigmatism"], auth: "public", handlerName: "astigmatismPreviewJson" }
];
